config/routes.rb
Rails.application.routes.draw do



  devise_for :customers,skip:[:passwords],controllers:{
    registrations:"public/registrations",
    sessions:'public/sessions'
  }

  devise_for :admin,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }

  namespace :public do
    root :to => 'homes#top'
    get 'about' => 'homes#about'

     get 'costomers/confirm' => 'customers#confirm'
    patch 'customers/unsubscribe' => 'customers#unsubscribe'
     get'orders/confirm' => 'orders#confirm'
     resources :items, only: [:show,:index]
     resources :customers, only: [:show, :edit, :update]
     delete'cart_items/destroy_all' => 'cart_items#destroy_all'
     resources :cart_items, only: [:create,:index,:destroy]
     resources :orders, only: [:new,:create,:show,:index]
  end
  namespace :admin do
    root :to  => 'homes#top'
  end
  namespace :admin do
    get 'genres/index'
    get 'genres/edit'
  end
  namespace :admin do
    get 'index' => 'items#index'
    resources :items, only: [:new,:create,:show,:edit,:update]
    resources :genres, only: [:index,:create,:edit,:update]
    resources :customers, only: [:show,:index,:edit,:update,]

  end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def address_display
  '〒' + ship_postal_code + ' ' + ship_to_address + ' ' + ship_name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  has_one_attached :item_image
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price*amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :cart_items, dependent: :destroy
   has_many :orders, dependent: :destroy
   has_many :address, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (price*1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  enum payment_method:{credit_card:0,transfer:1}
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :ite
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def index
    @customers = Customer.all
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana,:first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController


 def create
   genre = Genre.new(genre_params)
   genre.save
   redirect_to admin_genres_path
 end

 def index
   @genre = Genre.new
   @genres = Genre.all
 end

 def edit
   @genre = Genre.find(params[:id])
 end

 def update
   genre = Genre.find(params[:id])
   genre.update(genre_params)
   redirect_to admin_genres_path
 end

 private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item =Item.new
    
  end

  def create
    @item = Item.new(item_params)
    if @item.save
    redirect_to admin_index_path
    else
    render :new
    
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       redirect_to admin_item_path(@item.id)
    else
       render :edit
    end
  end

  private
   def item_params
     params.require(:item).permit(:item_image, :name, :introduction, :price, :is_active ,:genre_id)
   end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_out_path_for(resource)
    public_root_path # ログアウト後に遷移するpath
  end

  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h3><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h3>


<table>
  <thead>
    <tr>
      <th></th>
      <th></tgh>
    </tr>
  </thead>
  <%= form_with model: @customer, url: admin_customer_path do |f| %>
  <tbody>
    <tr>
      <td>会員ID</td>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= f.text_field :last_name %><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><%= f.text_field :postal_code %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= f.text_field :address %></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><%= f.text_field :telephone_number %></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <td><%= f.radio_button :is_deleted, :false %>
          <%= f.label :is_active,"有効" %>

          <%= f.radio_button :is_deleted, :true %>
          <%= f.label :is_active,"退会" %>
      </td>
    </tr>
  </tbody>
</table>
  <%= f.submit "変更を保存", class:"btn btn-success" %>
  <% end %>

app/views/admin/customers/index.html.erb
<h1>会員一覧</h1>

<table class="table table-hover table-inverse">
    <thead>
      <tr>
       <th>会員ID</th>
       <th>氏名</th>
       <th>メールアドレス</th>
       <th>ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @customers.each do |customer| %>
       <tr>
         <td><%= customer.id %></td>
         <td><%= link_to admin_customer_path(customer.id) do %>
             <%= customer.last_name %><%= customer.first_name %>
             <% end %>
         </td>
         <td><%= customer.email %></td>
         <td><% if customer.is_deleted == false %>有効
             <% else %>退会
             <% end %>
         </td>
       </tr>
      <% end %>
    </tbody>
  </table>

app/views/admin/customers/show.html.erb
<h1><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></tgh>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>会員ID</td>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= @customer.last_name %><%= @customer.first_name %></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <td><% if @customer.is_deleted == false %>有効
          <% else %>退会
          <% end %>
      </td>
    </tr>
  </tbody>
</table>
<%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-sm btn-success"%>

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集</h1>


<%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>

<table class="table">
  <tbody>
       <tr>
         <td>ジャンル名</td>
         <td><%= f.text_field :name %></td>
         <td><%= f.submit"変更を保存", class:"btn btn-success" %></td>
       </tr>
  </tbody>
</table>
<% end %>

app/views/admin/genres/index.html.erb
<h1>ジャンル一覧・追加</h1>

<%= form_with model: @genre, url: admin_genres_path do |f| %>

<div class="form-group">
  <label for="genre_name">ジャンル名</label>
  <input class="form-control genre_name"<%= f.text_field :name %>
</div>

<div class="form-group">
  <input class="btn btn-secondary"<%= f.submit '新規登録' %>
</div>
<% end %>

<table class="table table-hover table-inverse">
    <thead>
      <tr>
       <th>ジャンル</th>
       <th></th>
      </tr>
    </thead>

    <tbody>
      <% @genres.each do |genre| %>
       <tr>
         <td><%= genre.name %></td>
         <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-sm btn-success"%></td>
       </tr>
      <% end %>
    </tbody>
  </table>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>

<%= form_with model: @item, url: admin_item_path do |f| %>
<div class="form-group">
  <label>商品画像</label>
    <%= f.file_field :item_image %></div>
  <label>商品名</label>
    <%= f.text_field :name %>
  <label>商品説明</label>
    <%= f.text_field :introduction %>
  <label>ジャンル</label>
    <%= f.collection_select(:genre_id,Genre.all,:id,:name,{ include_blank: true, selected:'選択'}) %>
  <label>税抜価格</label>
    <%= f.text_field :price %>
  <label>販売ステータス</label>
    <%= f.radio_button :is_active, :true %>
    <%= f.label :is_active,"販売中" %>

    <%= f.radio_button :is_active, :false %>
    <%= f.label :is_active,"販売停止中" %>

</div>
    <%= f.submit "変更を保存", class:"btn btn-success" %>
<% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>


<table class="table table-hover table-inverse">
    <thead>
      <tr>
       <th>商品ID</th>
       <th>商品名</th>
       <th>税抜価格</th>
       <th>ジャンル</th>
       <th>ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
       <tr>
         <td><%= item.id %></td>
         <td><%= item.name %></td>
         <td><%= item.price %></td>
         <td><%= item.genre.name %></td>
         <td><% if item.is_active == true  %>販売中
             <% else %>販売停止中
             <% end %>
         </td>
       </tr>
      <% end %>
    </tbody>
  </table>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>



<%= form_with model: @item, url: admin_items_path do |f| %>

<div class="form-group">
  <label for="item_image">商品画像</label>
  <%= f.file_field :item_image %>
</div>

<div class="form-group">
  <label for="name">商品名</label>
  <input class="form-control name"<%= f.text_field :name %>
</div>

<div class="form-group">
  <label for="item_introduction">商品説明</label>
  <textarea class="form-control introduction"<%= f.text_area :introduction %>

</div>

<div class="form-group">
  <label for="genre">ジャンル</label>
  <%= f.collection_select(:genre_id,Genre.all,:id,:name,{ include_blank: true, selected:'選択'}) %>

</div>

<div class="form-group"
  <label for="price">税抜価格</label>
  <input class="form-control name"<%= f.text_field :price %>円
</div>

<div class="form-group">
  <label for="is_active">販売ステータス</label>
   <%= f.radio_button :is_active, :true %>
   <%= f.label :is_active,"販売中" %>

   <%= f.radio_button :is_active, :false %>
   <%= f.label :is_active,"販売停止中" %>
</div>

<div class="form-group">
  <input class="btn btn-secondary"<%= f.submit '新規登録' %>
</div>



<% end %>

app/views/admin/items/show.html.erb
<p id="notice"></p>
<h1>商品詳細</h1>

<div><%= image_tag @item.item_image, size:"300x200" %></div>
<div>商品名</div>
<div><%= @item.name %></div>

<div>商品説明</div>
<div><%= @item.introduction %></div>

<div>ジャンル</div>
<div><%= @item.genre.name %></div>

<div>税込価格</div>
<div>（税抜価格）</div>
<div><%= (@item.price*1.1).floor %>(<%= @item.price %>)円</div>

<div>販売ステータス</div>
<div><%= @item.is_active %></div>

<%= link_to "編集する",  edit_admin_item_path(@item.id), class:"btn btn-sm btn-success"%>